[[redirects]]
  from = “/youtube/v3/search”
  to = “https://www.googleapis.com"
  status = 200
[[redirects]]
  from = “/youtube/v3/videos”
  to = “https://youtube.googleapis.com”
  status = 200
  [[redirects]]
  from = “/complete”
  to = “https://suggestqueries.google.com”
  status = 200